import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import SiteFooter from "../components/SiteFooter";
import CareersOpenings from "./CareersOpenings";

export const metadata: Metadata = {
  title: "Careers",
  description: "Careers at Falcon.",
};

const SERIF = "var(--font-libre-baskerville), Georgia, serif";
const GEIST = "var(--font-geist-sans), sans-serif";

const OPENINGS = [
  {
    title: "Content Lead",
    description:
      "Own Falcon's public voice. You turn what the product sees into writing people share, and build the audience that becomes our first thousand users.",
    details: [
      "Falcon produces something rare: a daily stream of research a desk would charge for, generated by a machine that never sleeps. Your job is to decide which of it the world gets to see, and to write it so well that people forward it. You'll own every public word we publish: the signal write-ups, the launch posts, the threads that explain how one company's bad quarter becomes another's problem three hops down the supply chain.",
      "Day to day, you'll work directly with the founders and the research output itself. You pick the story, pressure-test it against the data, write it, ship it, and watch what lands. Over time you build the playbook: what we publish, where, in what voice, and how it compounds into an audience that trusts us before they ever open the app.",
      "You should write clearly under your own name, understand markets well enough to smell a weak claim, and want the numbers on your work. Portfolio over resume: show us three things you wrote that strangers shared.",
    ],
  },
  {
    title: "Community Manager",
    description:
      "Run the tester program end to end. You onboard new users, collect what confuses them, turn feedback into reports the team acts on, and keep the advisory group engaged as we move toward launch.",
    details: [
      "The first hundred people inside Falcon decide what it becomes, and you're the person they all know. You run the tester program end to end: onboarding every new member personally, watching where they get stuck, and turning what confuses them into reports the team actually acts on. When something breaks at midnight, you're the one who knows which three users hit it and what they were doing.",
      "You'll own the advisory group too: the traders who applied early, got in, and now shape the roadmap. Keeping them engaged means real conversations about how they trade, not newsletter blasts. What they tell you becomes the sharpest input the product team has.",
      "You should be organized enough to track fifty parallel conversations without dropping one, direct enough to tell us when something we shipped is bad, and genuinely curious about how retail traders work. Experience running a Discord, a beta program, or a trading community counts for a lot here.",
    ],
  },
  {
    title: "Research Analyst",
    description:
      "Pressure-test Falcon's output before anyone else sees it. You know how companies connect through supply chains, and you can tell a real second-order effect from a coincidence.",
    details: [
      "Every signal Falcon publishes carries our name, and your job is to be the last skeptic it meets before anyone else sees it. The engine maps how companies connect through supply chains, customers, and filings, then argues that news at one company should move another. You decide whether that argument survives contact with reality: is the relationship still live, is the exposure big enough to matter, and would a desk analyst nod or wince.",
      "Day to day, you review the day's second-order signals against filings and reporting, kill the ones that don't hold, and write the reasoning for the ones that do. What you flag feeds straight back into how the engine scores relationships, so your judgment compounds: every call you make teaches the system something.",
      "You should read 10-Ks for fun, know the difference between a supplier that matters and one that shows up in a list, and be comfortable saying \"this is wrong\" to a model that's confident. Buy-side, sell-side, or serious independent research all work; a sample of your thinking beats any credential.",
    ],
  },
];

const TAGS = ["Remote", "Flexible"];

// The old internships content lives in JobsApplyForm.tsx if it comes back.
export default function CareersPage() {
  return (
    <div className="bg-[#fdfdfd] text-[#111111]">
      <Navbar />
      {/* Full-viewport stage: the footer stays below the fold. */}
      <main className="mx-auto min-h-[100svh] w-full max-w-7xl px-6 pt-40 sm:px-10">
        <h1
          className="max-w-xl"
          style={{
            fontFamily: SERIF,
            fontWeight: 400,
            fontSize: "48px",
            lineHeight: "48px",
            color: "rgb(29, 27, 27)",
          }}
        >
          Let&apos;s build something traders actually trust.
        </h1>
        <p
          className="mt-6 max-w-xl"
          style={{
            fontFamily: GEIST,
            fontWeight: 400,
            fontSize: "17px",
            lineHeight: "26px",
            color: "rgb(140, 140, 140)",
          }}
        >
          Small team, early days, hard problems worth solving. Come build with us.
        </p>

        <CareersOpenings openings={OPENINGS} tags={TAGS} />
      </main>
      <SiteFooter />
    </div>
  );
}
